### ISSUE TITLE
공용 Docs Gitbook 개선

### ISSUE THREAD

**Issue by robert-min** [C-auto/infra-lab#3]
### 🙋🏻‍♂️ 요구사항
- gitbook 작성자, 작성일자가 컨텐츠 내에 보이도록 환경 구축
- 리뷰어 지정 자동화 할 수 있는 git action 추가
- gitbook 가이드 작성

<br>

### 🧑‍💻 Todo
- [x] gitbook에 글 작성자, 작성일자 보이도록 기능 추가
- [ ] 리뷰어 지정 자동화 git action 추가
- [x] 가이드 작성

**Comment by robert-min** [comment]
## Git action을 활용한 gitbook 자동화

### 요구사항 적용
1. gitbook 작성자, 작성일자가 컨텐츠 내에 보이도록 환경 구축
- 현재 리서치를 했을 때 gitbook 자체적으로 컨텐츠 업로드 한 작성자와 작성(수정)일자를 보일 수 있는 기능은 없는 것으로 확인
- 작성자, 작성일자가 컨텐츠에 보이기 위해서는 작성자가 직접 본인의 md 파일에 해당 값을 넣어야하면 이렇게 할 경우 사용자 입장에서 불편할 것으로 생각
- 작성자는 기존 방식으로 콘텐츠를 작성하고 배포할 때 자동으로 Git action을 통해 작성자, 작성일자가 컨텐츠 상에 등록되도록 기능 구현
2. 리뷰어 지정 자동화 할 수 있는 git action 추가
- gitbook 배포 전 Reviewer 지정을 자동화 할 수 있는 git action을 함께 추가하여 업로드 과정에서 불편함을 최소화 할 수 있도록 기능 구현
3. gitbook 가이드 작성
- 위의 git action 작업 완료 후 사용자 가이드 작성
- 가이드 작업 완료 후 사용자 피드백 진행

**Comment by robert-min** [comment]
## gitbook 글 작성자, 작성일자 보이도록 기능 추가
- PR과정에서 push할 때 자동으로 작성자 아이디와 업데이트 날짜 보이도록 git action 추가
- 처음에는 현재 PR 중인 브런치와 main 브런치 사이의 변경사항을 비교해서 파일을 수정하도록할 예정이었으나 작업 과정에서 어려움이 있어 브런치명과 작업할 파일명을 동일하게 하는 방향으로 진행
- gitbook에 새로운 글을 작성하게 위해서는 아래 규칙으로 진행 필요

1. python 카테고리에 hello_python.md라는 파일로 글 작성한다고 가정
2. 해당 글을 github에 업로드하기위해서 브런치 명은 `python/hello_python`으로 생성해야 함.
3. PR생성 후 사용자가 원격저장소에 푸시하면 브런치 명을 기준으로 파일을 찾아서 글 작성자, 작성일자가 자동으로 추가됨.

- 현재 git action은 branch에 푸시될때마다 하도록 설정되어 있으나(테스트하기 편하도록) 나중에는 최종적으로 merge할 때 한번만 실행하게 수정하면 좋을 듯

### git action 코드
- add_metadata.yml

```yml
name: Add Metadata to Markdown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find and update Markdown file
        id: find_file
        run: |
          md_file="${{ github.event.pull_request.head.ref }}.md"
          echo $md_file
          if [[ -n "$md_file" ]]; then
            echo "Found Markdown file: $md_file"
            
              if grep -q "<span style=\"background-color:#fff5b1\">Author : " "$md_file"; then
                echo "Removing existing <span> tag from the first line."
                sed -i '1s/<span.*span>//i' "$md_file"
              fi
            sed -i "1i <span style=\"background-color:#fff5b1\">Author : $GITHUB_ACTOR / Last Update : $(date +'%Y-%m-%d')</span>" "$md_file"
          else
            echo "No Markdown files found."
            exit 1
          fi
      - name: Commit and push changes
        run: |
          git config --global user.email "robert-min@github.com"
          git config --global user.name $GITHUB_ACTOR
          git checkout -b ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -m "Add metadata to Markdown file"
          git push -f --set-upstream origin ${{ github.event.pull_request.head.ref }}
```

**Comment by robert-min** [comment]
## gitbook 글 작성자, 작성일자 기능 수정
### 문제상황
- 기존에 코드의 경우 md 파일의 첫번째 줄에다가 작성자, 수정일자를 추가
- 이렇게 진행할 경우 gitbook에서 해당 컨텐츠 제목을 컨텐츠 제목이 아닌 파일명으로 설정하는 문제 확인

<img width="811" alt="스크린샷 2023-08-02 오후 11 43 25" src="https://github.com/C-auto/infra-lab/assets/91866763/9eb1e713-d21a-41eb-bf3f-44649e51c4b3">

<br>

### 해결방안
- 기존에 상단에 추가된 태그를 문서 가장 아래로 수정
- 수정된 코드 
- add_metadata.yml

```yml
name: Add Metadata to Markdown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find and update Markdown file
        id: find_file
        run: |
          md_file="${{ github.event.pull_request.head.ref }}.md"
          echo $md_file
          if [[ -n "$md_file" ]]; then
            echo "Found Markdown file: $md_file"
            
            if grep -q "<span style=\"background-color:#fff5b1\">Author : " "$md_file"; then
                echo "Removing existing <span> tag from the last line."
                sed -i '$s/<span.*span>//i' "$md_file"
            fi

            echo "<span style=\"background-color:#fff5b1\">Author : $GITHUB_ACTOR / Last Update : $(date +'%Y-%m-%d')</span>" >> "$md_file"

          else
            echo "No Markdown files found."
            exit 1
          fi
      - name: Commit and push changes
        run: |
          git config --global user.email "robert-min@github.com"
          git config --global user.name $GITHUB_ACTOR
          git checkout -b ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -m "Add metadata to Markdown file"
          git push -f --set-upstream origin ${{ github.event.pull_request.head.ref }}

```
- 수정 결과
  - 상단 제목보이도록 문제 해결
<img width="803" alt="스크린샷 2023-08-02 오후 11 52 12" src="https://github.com/C-auto/infra-lab/assets/91866763/22c62a08-4a99-4bc2-814d-238cf02e663c">

  - 작성자 및 수정일자 아래로 이동
<img width="790" alt="스크린샷 2023-08-02 오후 11 52 24" src="https://github.com/C-auto/infra-lab/assets/91866763/6f36ec58-d44a-4029-a69a-acff532e76dd">
